# Generated by Django 5.0.13 on 2025-04-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0006_semester_semcourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=10, unique=True)),
                ('schedule', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UMS.faculty')),
                ('sem_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UMS.semcourses')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
