# Generated by Django 5.0.13 on 2025-04-05 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0007_courseassign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseassign',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UMS.departassign'),
        ),
    ]
