# Generated by Django 5.0.13 on 2025-04-15 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0008_alter_courseassign_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(to='UMS.studentimage')),
                ('sem_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UMS.semcourses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UMS.student')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'sem_course'), name='unique_student_semcourse'),
        ),
    ]
