# Generated by Django 5.0.13 on 2025-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0009_enrollment_enrollment_unique_student_semcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Withdrawn', 'Withdrawn')], default='Active', max_length=20),
        ),
    ]
