# Generated by Django 5.0.13 on 2025-04-26 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0010_enrollment_enrollment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sem_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UMS.semcourses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
