# Generated by Django 5.0.14 on 2025-05-13 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0011_attendances'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('stud_attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('attendance_status', models.CharField(max_length=20)),
                ('attendance_date', models.DateField()),
                ('student_name', models.CharField(blank=True, max_length=255)),
                ('course_name', models.CharField(blank=True, max_length=255)),
                ('is_mark', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UMS.attendances')),
                ('enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UMS.enrollment')),
            ],
        ),
    ]
