# Generated by Django 5.0.14 on 2025-05-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0013_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(choices=[('ip', 'IP Camera'), ('device', 'Device Camera')], default='device', max_length=10),
        ),
        migrations.AddField(
            model_name='camera',
            name='endpoint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='port',
            field=models.IntegerField(blank=True, default=80, null=True),
        ),
    ]
