# Generated by Django 5.0.14 on 2025-05-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0014_camera_camera_type_camera_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='device_index',
            field=models.PositiveIntegerField(blank=True, help_text='0 for default webcam', null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(choices=[('local', 'Local / USB webcam'), ('ip', 'HTTP-MJPEG (DroidCam, ESP32-cam, …)'), ('rtsp', 'RTSP stream (CCTV, NVR, etc.)')], default='device', max_length=10),
        ),
    ]
