# Generated by Django 5.0.14 on 2025-05-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0015_camera_device_index_alter_camera_camera_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(choices=[('local', 'Local '), ('ip', 'DroidCam'), ('rtsp', 'RTSP stream ')], default='local', max_length=10),
        ),
    ]
