# Generated by Django 5.0.14 on 2025-05-23 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UMS', '0016_alter_camera_camera_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='device_index',
        ),
    ]
